on:
  push:
  pull_request:
  
name: Python Code Lint Check
jobs:
  lintpython:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.10.12
    - uses: marian-code/python-lint-annotate@v4
      with:
        python-root-list: "**/*.py"
        use-black: true
        use-isort: false
        use-mypy: false
        use-pycodestyle: false
        use-pydocstyle: false
        # extra-pycodestyle-options: "--max-line-length=88"
        use-pylint: false
        use-flake8: false
        use-vulture: false
        python-version: "3.10.12"
