on:
  push:
  pull_request:
  
name: Python Code Lint Check
jobs:
  lintpython:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ricardochaves/python-lint@v1.4.0
