on:
  push:
  pull_request:
  
name: Python Code Lint Check
jobs:
  lintpython:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - run: |
        python --version  # this will output 3.9 now
        run tests or other things using python ...
    - uses: marian-code/python-lint-annotate@v4
      with:
        python-root-list: "*.py"
        use-black: true
        # use-isort: true
        # use-mypy: true
        # use-pycodestyle: true
        # use-pydocstyle: true
        # extra-pycodestyle-options: "--max-line-length=88"
        # use-pylint: false
        # use-flake8: false
        # use-vulture: true
        python-version: "3.8"
    - run: |
        python --version  # this will output 3.8 now !!!
