on:
  push:
  pull_request:
  
name: Code Linting Checks
jobs:
  lintpython:
    name: Check Python Code Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install IPO Alert dependencies
        run: |
          python -m pip install -r ipo-alert/requirements.txt
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint --disable=R,C $(git ls-files '*.py')
