on:
  push:
  pull_request:
  
name: Python Code Lint Check
jobs:
  lintpython:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install -r ipo-alert/requirements.txt
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "**/*.py"
          use-black: true
          use-pylint: true
          extra-pylint-options: "--disable=R,C"
